# api:
#   interval: 60s
#   uri: "http://requestb.in/13gerls1"
#   key: "48593282-b38d-4bf5-af58-f7327271e73d"
#   pid: "something-static"
# sessions:
#   uri: file:///tmp/transporter.state
#   interval: 2s
#   type: "filestore"
nodes:
  localmongo:
    type: mongodb
    uri: mongodb://user:pass@localhost/twitter?authSource=admin
    # uri: mongodb://localhost/twitter
    tail: true
    # Collection name db.Collection
    namespace: twitter.tweets
  es:
    type: elasticsearch
    uri: http://user:pass@localhost:9200/
    # uri: http://localhost:9200/
